services:
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=8Zb3bvhLp6o5evE1fUkmXCmwFQXpN2L8 --enable-cors'
